[workspace]
members = [
    "fuzzle",
    "duplicate_detector",
    "tag_search_engine",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = 'symbols'
overflow-checks = true  
