[workspace]
members = [
    "fuzzle",
    "duplicate_detector",
    "tag_search_engine",
]
resolver = "2"

[profile.release]
opt-level = 2
lto = 'thin'
codegen-units = 16
panic = 'abort'
strip = 'symbols'
overflow-checks = true  
