version: '3.8'
services:
  fuzzle:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: serve
    environment:
      - FUZZLE_TAG_DIR_PATH=/data/tags
      - FUZZLE_DB_FILE_PATH=/data/db.sqlite
      - FUZZLE_CONFIG_FILE_PATH=/config/config.toml
    volumes:
      # - fuzzle-data:/data
      - ./container-data:/data
      - .:/config:ro
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    restart: always

# volumes:
#   fuzzle-data: