CREATE TABLE IF NOT EXISTS tag (
    id TEXT NOT NULL PRIMARY KEY,
    category INTEGER NOT NULL,
    is_pending  BOOLEAN NOT NULL CHECK (is_pending IN (0, 1)) DEFAULT 1,
    dynamic_data TEXT NULL,
    created_by_user_id INTEGER NULL REFERENCES user(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE sticker_set ADD COLUMN created_by_user_id INTEGER NULL REFERENCES user(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
