# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"I\n\x14TextEmbeddingRequest\x12#\n\x05model\x18\x01 \x01(\x0e\x32\x14.inference.TextModel\x12\x0c\n\x04text\x18\x02 \x01(\t\"L\n\x15ImageEmbeddingRequest\x12$\n\x05model\x18\x01 \x01(\x0e\x32\x15.inference.ImageModel\x12\r\n\x05image\x18\x02 \x01(\x0c\"*\n\x11\x45mbeddingResponse\x12\x15\n\tembedding\x18\x01 \x03(\x02\x42\x02\x10\x01*\x1a\n\tTextModel\x12\r\n\tCLIP_TEXT\x10\x00*\x1c\n\nImageModel\x12\x0e\n\nCLIP_IMAGE\x10\x00\x32\xac\x01\n\x08Generate\x12N\n\rTextEmbedding\x12\x1f.inference.TextEmbeddingRequest\x1a\x1c.inference.EmbeddingResponse\x12P\n\x0eImageEmbedding\x12 .inference.ImageEmbeddingRequest\x1a\x1c.inference.EmbeddingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDDINGRESPONSE'].fields_by_name['embedding']._loaded_options = None
  _globals['_EMBEDDINGRESPONSE'].fields_by_name['embedding']._serialized_options = b'\020\001'
  _globals['_TEXTMODEL']._serialized_start=227
  _globals['_TEXTMODEL']._serialized_end=253
  _globals['_IMAGEMODEL']._serialized_start=255
  _globals['_IMAGEMODEL']._serialized_end=283
  _globals['_TEXTEMBEDDINGREQUEST']._serialized_start=30
  _globals['_TEXTEMBEDDINGREQUEST']._serialized_end=103
  _globals['_IMAGEEMBEDDINGREQUEST']._serialized_start=105
  _globals['_IMAGEEMBEDDINGREQUEST']._serialized_end=181
  _globals['_EMBEDDINGRESPONSE']._serialized_start=183
  _globals['_EMBEDDINGRESPONSE']._serialized_end=225
  _globals['_GENERATE']._serialized_start=286
  _globals['_GENERATE']._serialized_end=458
# @@protoc_insertion_point(module_scope)
