# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class GenerateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TextEmbedding = channel.unary_unary(
                '/inference.Generate/TextEmbedding',
                request_serializer=inference__pb2.TextEmbeddingRequest.SerializeToString,
                response_deserializer=inference__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.ImageEmbedding = channel.unary_unary(
                '/inference.Generate/ImageEmbedding',
                request_serializer=inference__pb2.ImageEmbeddingRequest.SerializeToString,
                response_deserializer=inference__pb2.EmbeddingResponse.FromString,
                _registered_method=True)


class GenerateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TextEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImageEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenerateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TextEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.TextEmbedding,
                    request_deserializer=inference__pb2.TextEmbeddingRequest.FromString,
                    response_serializer=inference__pb2.EmbeddingResponse.SerializeToString,
            ),
            'ImageEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.ImageEmbedding,
                    request_deserializer=inference__pb2.ImageEmbeddingRequest.FromString,
                    response_serializer=inference__pb2.EmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.Generate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Generate(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TextEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.Generate/TextEmbedding',
            inference__pb2.TextEmbeddingRequest.SerializeToString,
            inference__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImageEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.Generate/ImageEmbedding',
            inference__pb2.ImageEmbeddingRequest.SerializeToString,
            inference__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
