ALTER TABLE tag DROP COLUMN is_pending;
ALTER TABLE tag DROP COLUMN dynamic_data;
ALTER TABLE tag ADD COLUMN linked_channel_id INTEGER NULL;
ALTER TABLE tag ADD COLUMN linked_user_id INTEGER NULL;
ALTER TABLE tag ADD COLUMN aliases TEXT NULL;
ALTER TABLE tag ADD COLUMN implications TEXT NULL;

CREATE TABLE IF NOT EXISTS moderation_task (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_user_id INTEGER NOT NULL,
    details TEXT NOT NULL,
    completion_status INTEGER NOT NULL,
    FOREIGN KEY(created_by_user_id) REFERENCES user(id) ON UPDATE RESTRICT ON DELETE RESTRICT
);
