name: Bot API Docker Image

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform'
        required: true
        default: 'arm64'
        type: choice
        options:
        - arm64
        - amd64

jobs:
  docker_inference:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push (local-bot-api)
        uses: docker/build-push-action@v5
        with:
          context: local-bot-api
          platforms: linux/${{ inputs.platform }}
          push: true
          tags: ghcr.io/avoonix/fuzzle-bot-api:latest-${{ inputs.platform }}
